<a href="https://colab.research.google.com/github/Dawon00/Deep_Learning_Seminar/blob/master/learning_rate_and_evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


Instructions for updating:
non-resource variables are not supported in the long term
0 4.1773167 [[-1.3921032  -0.21185938  0.72048837]
 [-0.47774252 -0.97526526 -0.20281012]
 [ 0.9656      1.2878053  -0.01936202]]
1 2.2265296 [[-1.3821055  -0.25854865  0.7571799 ]
 [-0.3937801  -1.1567674  -0.10527047]
 [ 1.0582561   1.109308    0.06647916]]
2 1.8488889 [[-1.4151218  -0.2607663   0.7924139 ]
 [-0.54083276 -1.1021233  -0.01286193]
 [ 0.9286422   1.1569693   0.14843172]]
3 1.5264757 [[-1.415214   -0.29165345  0.82339317]
 [-0.51382303 -1.1969062   0.05491127]
 [ 0.9665303   1.0568733   0.21063961]]
4 1.3847282 [[-1.4325293  -0.29796752  0.8470226 ]
 [-0.5757099  -1.1639428   0.08383471]
 [ 0.9141789   1.0800599   0.23980448]]
5 1.3485234 [[-1.4332542  -0.3137169   0.86349684]
 [-0.54645026 -1.1779592   0.06859141]
 [ 0.9486957   1.0546813   0.23066625]]
6 1.3301777 [[-1.4429492  -0.3227359   0.8822108 ]
 [-0.56577027 -1.1589252   0.06887738]
 [ 0.9358621   1.0631046   0.23507647]]
7 1.3