<a href="https://colab.research.google.com/github/Dawon00/Deep_Learning_Seminar/blob/master/linear_regression_min_max.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow.compat.v1 as tf
import numpy as np
tf.disable_v2_behavior()


def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

# very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

Instructions for updating:
non-resource variables are not supported in the long term
[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [2]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(101):
        _, cost_val, hy_val = sess.run(
            [train, cost, hypothesis], feed_dict={X: x_data, Y: y_data}
        )
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2.7326443 
Prediction:
 [[-1.830496  ]
 [-1.4220743 ]
 [-1.1124777 ]
 [-0.70369005]
 [-1.0376042 ]
 [-0.8939028 ]
 [-0.28810322]
 [ 0.07532971]]
1 Cost:  2.732454 
Prediction:
 [[-1.8304132 ]
 [-1.4219965 ]
 [-1.112413  ]
 [-0.70364046]
 [-1.037545  ]
 [-0.8938457 ]
 [-0.28806654]
 [ 0.07536496]]
2 Cost:  2.7322636 
Prediction:
 [[-1.8303306 ]
 [-1.4219189 ]
 [-1.1123486 ]
 [-0.70359075]
 [-1.0374856 ]
 [-0.8937886 ]
 [-0.28802988]
 [ 0.0754002 ]]
3 Cost:  2.732073 
Prediction:
 [[-1.830248  ]
 [-1.4218411 ]
 [-1.112284  ]
 [-0.70354104]
 [-1.0374262 ]
 [-0.8937315 ]
 [-0.2879932 ]
 [ 0.07543546]]
4 Cost:  2.731883 
Prediction:
 [[-1.8301653 ]
 [-1.4217635 ]
 [-1.1122195 ]
 [-0.70349133]
 [-1.037367  ]
 [-0.8936744 ]
 [-0.28795654]
 [ 0.07547072]]
5 Cost:  2.7316928 
Prediction:
 [[-1.8300827 ]
 [-1.4216857 ]
 [-1.112155  ]
 [-0.70344174]
 [-1.0373076 ]
 [-0.8936173 ]
 [-0.28791985]
 [ 0.07550596]]
6 Cost:  2.731502 
Prediction:
 [[-1.83      ]
 [-1.4216081 ]
 [-1.1120903 ]
 [